### ISSUE TITLE
无法[在题目页面显示是否AC此题以及查看My Status及mark problem]

### ISSUE THREAD

**Issue by Cansult** [ranwen/BZOJHelper#1]
![](https://cansult.ga/pictures/20190212A.png)

系统为x64 ubuntu16.04

浏览器为firefox quantum 65.0 x64

在同学的win7 x64 chrome72.0.3626.96里也出现了同样的状况

怀疑是bzoj做了一点修改...

顺便表达一下支持...qwq

**Comment by ranwen** [comment]
已经解决 3808266

其实您冷静一下可以发现在您提出issue5分钟前就已经修复了（雾）

原因是BZOJ的Notice消失 但此项目内有过多的Magic Number导致js爆炸

**Comment by Cansult** [comment]
(～o￣3￣)～我那五分钟可能在找图床(雾
